# Generated by Django 4.2 on 2023-05-28 17:40

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nat_id',
            field=models.CharField(default=None, max_length=10, validators=[accounts.models.validate_iranian_nat_id]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09xxxxxxxxx'.", regex='^09\\d{9}$')]),
        ),
    ]
